//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hall
    {
        public int hall_id { get; set; }
        public string hall_name { get; set; }
        public Nullable<int> max_capacity { get; set; }
        public Nullable<System.DateTime> hall_date { get; set; }
        public Nullable<int> occ_id { get; set; }
    
        public virtual Occasion Occasion { get; set; }
    }
}
