//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int room_id { get; set; }
        public Nullable<int> room_no { get; set; }
        public string room_type { get; set; }
        public Nullable<int> room_price { get; set; }
        public string room_view { get; set; }
        public string meals { get; set; }
        public Nullable<System.DateTime> room_stdate { get; set; }
        public Nullable<System.DateTime> room_endate { get; set; }
        public string room_review { get; set; }
        public string add_req { get; set; }
        public Nullable<int> cust_id { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
